### ISSUE TITLE
Tutorial/Example implementation with Firebase

### ISSUE THREAD

**Issue by TJMusiitwa** [jonaird/upstate#1]
Hey there thank you for the work done to simplify state management for Flutter devs.
I was just inquiring that since upstate is still a very new package if you could run a an example implementation that uses Upstate for a few common implementations of firebase such as auth and firestore.
It would greatly help to raise the understanding of the package as most state management is about managing state of an authenticated user or interacting with a BaaS like firebase.
Thank you

**Comment by jonaird** [comment]
Hi, I don’t use Firebase so I’m not familiar with it. If you can give a very specific example of what you would need to do I may be able to help.

**Comment by logiczsniper** [comment]
I have used firestore with auth, I can give a try!

**Comment by logiczsniper** [comment]
https://github.com/logiczsniper/upstate_firestore_example
This only has authentication so far... I hope it helps 😀

**Comment by TJMusiitwa** [comment]
Alright then. Thanks alot, I'll check it out

Jonathan Musiitwa

________________________________

**Comment by jonaird** [comment]
Thanks @logiczsniper! Closing this issue, let me know if you have more questions.
